"""empty message

Revision ID: 1df234e9e92
Revises: None
Create Date: 2016-02-22 08:48:42.891990

"""

# revision identifiers, used by Alembic.
revision = '1df234e9e92'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('numbersequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generation_datetime', sa.DateTime(), nullable=True),
    sa.Column('sequence', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('numberapparition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_id', sa.Integer(), nullable=True),
    sa.Column('apparition_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['number_id'], ['number.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('numberapparition')
    op.drop_table('numbersequence')
    op.drop_table('number')
    ### end Alembic commands ###
